---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-java

inputs:
  - name: dp-java-duration-parse

outputs:
  - name: build

params:
  APPLICATION:
  
run:
  path: dp-java-duration-parse/ci/scripts/build.sh
