---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.12.0

inputs:
  - name: dp-java-duration-parse

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-java-duration-parse/ci/scripts/build.sh
